# This workflow will install Python dependencies, and package the Lambda function

name: Package and release support-collector-lambda

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Package Lambda
      run: |
        cd src/support_collector
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t temp_dir/ ; fi
        cp -r temp_dir/* support-collector-lambda/
    - uses: actions/upload-artifact@v4
      with:
        name: support-collector-lambda.zip
        path: src/support_collector/support-collector-lambda/*
        compression-level: 9
        if-no-files-found: error
  
  release:
    needs: build
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: support-collector-lambda.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: support-collector-lambda.zip
        make_latest: true
